name: xaxino
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  animated_floating_buttons: ^0.0.2
  audioplayers: ^6.0.0
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.0.2
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.1.1
  circular_countdown_timer: ^0.2.3
  connectivity_plus: ^6.0.3
  country_picker: ^2.0.11
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  dotted_border: ^2.0.0+2
  file_picker: ^8.0.3
  firebase_analytics: ^10.7.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: ^14.7.19
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.1
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^17.1.2
  flutter_slot_machine: ^0.0.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  flutter_widget_from_html: ^0.15.0
  gallery_saver: ^2.3.2
  get: ^4.6.6
  google_fonts: ^4.0.4
  google_sign_in: ^6.2.1
  html: ^0.15.4
  http: ^0.13.4
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  json_annotation: ^4.9.0
  lottie: ^3.0.0
  path_drawing: ^1.0.1
  path_provider: ^2.0.9
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  roller_list: ^1.0.3
  share_plus: ^9.0.0
  shared_preferences: ^2.0.13
  shimmer: ^3.0.0
  show_up_animation: ^2.0.0
  simple_animations: ^5.0.2
  url_launcher: ^6.2.6
  zoom_tap_animation: ^1.1.0
  # webview_flutter_android: ^3.16.2
  

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/images/splash_screen/
    - assets/images/login/
    - assets/images/games/
    - assets/images/dashboard/
    - assets/images/nav_bar/
    - assets/images/spin/
    - assets/images/dashboard/
    - assets/images/wallet/
    - assets/animation/
    - assets/font-family/
    - assets/images/logo/
    - assets/animation/

  fonts:
    - family: Semakin
      fonts:
        - asset: assets/font-family/Semakin.otf
    - family: Inter
      fonts:
        - asset: assets/font-family/Inter-Regular.ttf
